### ISSUE TITLE
Can't create barrel files on Windows

### ISSUE THREAD

**Issue by RosilBelli** [mikededo/dartBarrelFileGenerator#9] opened 2021-04-21 01:00 UTC
I'm running vs code on Windows 10 and I'm not being able to create barrel files on my project (a package).

I just get an error message on vs code: GDBF: Error on generating the file.

These are my environment versions: 
Version: 1.55.2 (user setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:35:57.887Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by mikededo** [comment] 2021-04-21 07:40
Hello @RosilBelli 👋🏼

Currently I'm a bit busy, but as soon as I can I will put my hands into it. Does it only happen with this project? Have you tried if the error happens always in your environment?

If you could provide a small set up where I could test the error would be very helpful!

**Comment by mikededo** [comment] 2021-04-25 06:09
Hello @RosilBelli!

I've been testing it out in Windows machines and I do not have any issue! I'm also closing this issue since no more information has been provided.

If the problem persists, feel free to reopen the issue 😉

**Comment by RosilBelli** [comment] 2021-04-25 12:58
Hi @mikededo!

Sorry for the delay to respond. I think I got the error point.
The above project environment is under a vscode workspace. If I use the extension on a project that is not within a workspace it works perfectly, but those inside a workspace do not.

**Comment by mikededo** [comment] 2021-04-25 13:58
Hm, have you tried it with the version `1.3.0`, which has been upload this morning?  
I have changed the way files are managed, maybe it has indirectly solved your problem (or so I think).

If you can try it and give me feedback I will appreciate it 😉

**Comment by RosilBelli** [comment] 2021-04-25 15:20
Hi @mikededo!

I updated now the extension but it is still not working with version 1.3.0 on the project under the workspace.

**Comment by MalcolmBB** [comment] 2022-08-11 09:43
Hey @mikededo 

I'm still experiencing this same issue with the project under the workspace in v4.0.0

Works perfectly if not within a workspace as mentioned above.

**Comment by mikededo** [comment] 2022-08-12 14:20
Hi @MalcolmBB!

I have reopened the issue and I will give it a look during the weekend. I have just started holidays so it may take a bit. Sorry for not keeping track with the issue.

**Comment by MalcolmBB** [comment] 2022-08-13 13:31
Thanks, @mikededo! 

Have a good weekend!

**Comment by mikededo** [comment] 2022-08-16 06:29
Hi @RosilBelli and @MalcolmBB!
I have been trying to recreate the issue but not succeeded. Would it be possible for you to provide a `.code-workspace` file for me to test in which the extension would fail?

**Comment by MalcolmBB** [comment] 2022-08-16 07:34
Hi @mikededo, I don't have one available at the moment but I believe the issue arises when you have a workspace with multiple projects in it. Please let me know if this configuration displays the issue, if not I will try and get a sharable workspace file to you.

**Comment by mikededo** [comment] 2022-09-02 06:12
Hi @RosilBelli and @MalcolmBB! I have good and bad news for you!  
I have been able to figure out why the issue is happening and found a temporarilly solution. I also have a possible fix in mind but I'm afraid it would take me some time and currently I don't have much.

Basically, if you check your workspace file (`<some-name>.code-workspace`), you will see the props `files` that contains a list of `paths`. Each path is relative to the where the workspace file is located. For example, if I have my folder workspace in: `/a/d.code-workspace`, and the following file structure:

```sh
a
├── b
│   ├── c
│   └── e
└── d.code-workspace
```

If the `/a/b/c` and `/a/b/e` folders are added to the `d.code-workspace`, the workspace file will contain:

```jsonc
{
  "folders": [
    { "path": "b/c" },
    { "path": "b/d" },
  ]
  //...
}
```

As you can see this are relative paths, meaning that when the extension is run, the files paths are obtained from the workspace, meaning their are relative, and thus fail. The temporal solution would be to add the entire path of the folder on the workspace file configuration (which I have tested and works).

I hope this helps you! I'll be closing the issue as I will track this locally!

**Closed by mikededo** 2022-09-02 06:12 UTC
Labels: bug, help wanted, minor
